version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - mysql_data_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Strong@1234 # to be replaced
      MYSQL_DATABASE: chat_system
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
    volumes:
      - rabbitmq_dataa:/var/lib/rabbitmq  # Persist RabbitMQ data
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: Guest1234  # To be replaced

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.authc.api_key.enabled: false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.piStrongd && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Strong@1234
      DATABASE_DEV_NAME: chat_system
      REDIS_URL: redis://redis:6379/1
      ELASTICSEARCH_URL: elasticsearch:9200

volumes:
  mysql_data_vol:
  redis_data:
  rabbitmq_dataa:
  elasticsearch_data:
